"""CLI entry for building decks.

Usage:
  python -m slides_build.build --module M0
  python -m slides_build.build --module M1
  python -m slides_build.build --demo   (M0 + M1)

Side effect: each build also emits `output/_image_placeholders_{code}.yaml`
listing every image TODO in that deck (SOP §7).
"""
import argparse
from datetime import datetime
from pathlib import Path

from . import theme as T
from .slides import m0_deck, m1_deck


BUILDERS = {
    "M0": (m0_deck.build_m0, "M0_開場_Python與AI系統全景.pptx"),
    "M1": (m1_deck.build_m1, "M1_Python基礎與資料思維.pptx"),
}


def _dump_placeholders_yaml(code: str, registry: list, out_path: Path):
    """Write image placeholder audit YAML. Minimal dependencies — inline serializer."""
    lines = [
        f"# Auto-generated by slides_build.build for {code}",
        f"# {datetime.now().isoformat(timespec='seconds')}",
        f"# See shared/design_system/投影片生成_SOP_Agent工作流.md §7",
        "",
        f"module: {code}",
        f"total: {len(registry)}",
        f"pending: {sum(1 for r in registry if r['status'] == 'pending')}",
        "placeholders:",
    ]
    for r in registry:
        bb = r["bounding_box"]
        lines.extend([
            f"  - id: {r['id']}",
            f"    slot_name: \"{r['slot_name']}\"",
            f"    description: \"{r['description']}\"",
            f"    source_url: \"{r['source_url']}\"",
            f"    recommended_size: \"{r['recommended_size']}\"",
            f"    bounding_box: {{x: {bb['x']}, y: {bb['y']}, w: {bb['w']}, h: {bb['h']}}}",
            f"    status: {r['status']}",
            f"    asset_path: {r['asset_path'] or 'null'}",
        ])
    out_path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def build_module(code: str) -> Path:
    if code not in BUILDERS:
        raise ValueError(f"unknown module {code!r}; known: {list(BUILDERS)}")
    builder, filename = BUILDERS[code]
    out = T.OUTPUT_DIR / filename
    registry: list = []
    builder(out, image_registry=registry)

    if registry:
        yaml_path = T.OUTPUT_DIR / f"_image_placeholders_{code}.yaml"
        _dump_placeholders_yaml(code, registry, yaml_path)
        print(f"    ↳ placeholders audit: {yaml_path} ({len(registry)} pending)")

    return out


def main():
    ap = argparse.ArgumentParser()
    g = ap.add_mutually_exclusive_group(required=True)
    g.add_argument("--module", choices=list(BUILDERS))
    g.add_argument("--demo", action="store_true",
                   help="build M0 + M1 demo pair")
    args = ap.parse_args()

    targets = list(BUILDERS.keys()) if args.demo else [args.module]
    for code in targets:
        out = build_module(code)
        print(f"  ✓ {code}  →  {out}")


if __name__ == "__main__":
    main()
