"""CLI entry for building AI Fundamentals 實戰判斷力 (6 chapters) decks.

Usage:
  python -m slides_build.build --chapter Ch00
  python -m slides_build.build --all
"""
import argparse
import importlib
from datetime import datetime
from pathlib import Path

from . import theme as T


CHAPTERS = {
    "Ch00": ("ch00_deck", "build_ch00", "Ch00_AI全局地圖_先學會選武器.pptx"),
    "Ch01": ("ch01_deck", "build_ch01", "Ch01_統計作為AI的底盤.pptx"),
    "Ch02": ("ch02_deck", "build_ch02", "Ch02_機器學習_表格世界的主戰場.pptx"),
    "Ch03": ("ch03_deck", "build_ch03", "Ch03_深度學習_表徵學習.pptx"),
    "Ch04": ("ch04_deck", "build_ch04", "Ch04_生成式AI_系統工程.pptx"),
    "Ch05": ("ch05_deck", "build_ch05", "Ch05_評估與治理_可上線系統.pptx"),
}


def _dump_placeholders_yaml(code: str, registry: list, out_path: Path):
    lines = [
        f"# Auto-generated by slides_build.build for {code}",
        f"# {datetime.now().isoformat(timespec='seconds')}",
        "",
        f"chapter: {code}",
        f"total: {len(registry)}",
        f"pending: {sum(1 for r in registry if r['status'] == 'pending')}",
        "placeholders:",
    ]
    for r in registry:
        bb = r["bounding_box"]
        lines.extend([
            f"  - id: {r['id']}",
            f"    slot_name: \"{r['slot_name']}\"",
            f"    description: \"{r['description']}\"",
            f"    source_url: \"{r['source_url']}\"",
            f"    recommended_size: \"{r['recommended_size']}\"",
            f"    bounding_box: {{x: {bb['x']}, y: {bb['y']}, w: {bb['w']}, h: {bb['h']}}}",
            f"    status: {r['status']}",
            f"    asset_path: {r['asset_path'] or 'null'}",
        ])
    out_path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def build_chapter(code: str) -> Path:
    if code not in CHAPTERS:
        raise ValueError(f"unknown chapter {code!r}; known: {list(CHAPTERS)}")
    module_name, func_name, filename = CHAPTERS[code]
    module = importlib.import_module(f".slides.{module_name}", package="slides_build")
    builder = getattr(module, func_name)
    out = T.OUTPUT_DIR / filename
    registry: list = []
    builder(out, image_registry=registry)

    if registry:
        yaml_path = T.OUTPUT_DIR / f"_image_placeholders_{code}.yaml"
        _dump_placeholders_yaml(code, registry, yaml_path)
        print(f"    ↳ placeholders audit: {yaml_path} ({len(registry)} pending)")

    return out


def main():
    ap = argparse.ArgumentParser()
    g = ap.add_mutually_exclusive_group(required=True)
    g.add_argument("--chapter", choices=list(CHAPTERS))
    g.add_argument("--all", action="store_true", help="build all 6 chapters")
    args = ap.parse_args()

    targets = list(CHAPTERS.keys()) if args.all else [args.chapter]
    for code in targets:
        try:
            out = build_chapter(code)
            print(f"  ✓ {code}  →  {out}")
        except Exception as e:
            print(f"  ✗ {code}  FAILED: {e}")


if __name__ == "__main__":
    main()
