"""CLI entry for building Python DA/DE Course (12h, S1-S6) decks.

Usage:
  python -m slides_build.build --session S1
  python -m slides_build.build --all

Each session targets 22-28 content slides aligned to teacher_notes/SN_teacher_notes.md.
Follows teaching-track golden rules (shared/design_system/教學型投影片_黃金守則與泛式.md).
"""
import argparse
import importlib
from datetime import datetime
from pathlib import Path

from . import theme as T


SESSIONS = {
    "F1": ("f1_deck", "build_f1", "F1_計算機概論與OS角色.pptx"),
    "F2": ("f2_deck", "build_f2", "F2_Python核心與資料結構深化.pptx"),
    "F3": ("f3_deck", "build_f3", "F3_OOP核心觀念與實例化.pptx"),
    "F4": ("f4_deck", "build_f4", "F4_封裝繼承與魔術方法.pptx"),
    "F5": ("f5_deck", "build_f5", "F5_OOP_Pandas整合實戰.pptx"),
    "S1": ("s1_deck", "build_s1", "S1_NumPy與向量化思維.pptx"),
    "S2": ("s2_deck", "build_s2", "S2_Pandas_IO與資料清理.pptx"),
    "S3": ("s3_deck", "build_s3", "S3_Pandas轉換_groupby_merge_pivot.pptx"),
    "S4": ("s4_deck", "build_s4", "S4_時間序列與EDA實戰.pptx"),
    "S5": ("s5_deck", "build_s5", "S5_視覺化精華_五種必懂圖.pptx"),
    "S6": ("s6_deck", "build_s6", "S6_Plotly互動與Capstone.pptx"),
}


def _dump_placeholders_yaml(code: str, registry: list, out_path: Path):
    lines = [
        f"# Auto-generated by slides_build.build for {code}",
        f"# {datetime.now().isoformat(timespec='seconds')}",
        "",
        f"session: {code}",
        f"total: {len(registry)}",
        f"pending: {sum(1 for r in registry if r['status'] == 'pending')}",
        "placeholders:",
    ]
    for r in registry:
        bb = r["bounding_box"]
        lines.extend([
            f"  - id: {r['id']}",
            f"    slot_name: \"{r['slot_name']}\"",
            f"    description: \"{r['description']}\"",
            f"    source_url: \"{r['source_url']}\"",
            f"    recommended_size: \"{r['recommended_size']}\"",
            f"    bounding_box: {{x: {bb['x']}, y: {bb['y']}, w: {bb['w']}, h: {bb['h']}}}",
            f"    status: {r['status']}",
            f"    asset_path: {r['asset_path'] or 'null'}",
        ])
    out_path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def build_session(code: str) -> Path:
    if code not in SESSIONS:
        raise ValueError(f"unknown session {code!r}; known: {list(SESSIONS)}")
    module_name, func_name, filename = SESSIONS[code]
    module = importlib.import_module(f".slides.{module_name}", package="slides_build")
    builder = getattr(module, func_name)
    out = T.OUTPUT_DIR / filename
    registry: list = []
    builder(out, image_registry=registry)

    if registry:
        yaml_path = T.OUTPUT_DIR / f"_image_placeholders_{code}.yaml"
        _dump_placeholders_yaml(code, registry, yaml_path)
        print(f"    ↳ placeholders audit: {yaml_path} ({len(registry)} pending)")

    return out


def main():
    ap = argparse.ArgumentParser()
    g = ap.add_mutually_exclusive_group(required=True)
    g.add_argument("--session", choices=list(SESSIONS))
    g.add_argument("--all", action="store_true", help="build all 6 sessions")
    args = ap.parse_args()

    targets = list(SESSIONS.keys()) if args.all else [args.session]
    for code in targets:
        try:
            out = build_session(code)
            print(f"  ✓ {code}  →  {out}")
        except Exception as e:
            print(f"  ✗ {code}  FAILED: {e}")


if __name__ == "__main__":
    main()
